# Builds a docker image on pull requests
name: Build Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: docker build
        run: docker build -t python-playground .
      - name: run and ping the image 
        run: docker run -p 3838:3838 python-playground
      - name: curl
        run: curl http://127.0.0.1:3838 --max-time 30

