# Builds a docker image on pull requests
name: Build Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t berniegraves/shiny-dashboard:$(date +%s) .
      - name: run image
        run: docker run -dp 3838:3838 berniegraves/shiny-dashboard:$(date +%s)
      - name: Test endpoint
        run: curl http://127.0.0.1:3838
