name: Run Docker Image

on:
  push:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: berniegraves/shiny-dashboard

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: berniegraves/shiny-dashboard:$(date +%s)
          labels: ${{ steps.meta.outputs.labels }}
  # this job deosn't work yet -- error: cant find repository berniegraves/shiny-dashboard
  # try publishing to dockerhub and then pulling the image from there
  #
  run_image:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: pull the image from dockerhub
        run: docker pull berniegraves/shiny-dashboard:latest
      - name: Run the iamge
        run: docker run -dp 3838:3838 berniegraves/shiny-dashboard:latest
